In [5]:
# 1. Create a 1D NumPy Array:
# Create a 1D NumPy array named temperatures_w1 for Week 1 with the following values:
# [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
import numpy as np
temp_w1=[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
temp_w1=np.array(temp_w1)
temp_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [10]:
import numpy as np

# 1. Create a 1D NumPy Array for Week 1
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures Array:")
print(temperatures_w1)
print(f"Type: {type(temperatures_w1)}")
print(f"Shape: {temperatures_w1.shape}")
print(f"Data Type: {temperatures_w1.dtype}")

Week 1 Temperatures Array:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Type: <class 'numpy.ndarray'>
Shape: (7,)
Data Type: float64

In [6]:
#2. Inspection and Properties:
# Inspect the shape, data type, and the number of elements in the array.
# Inspect the shape of the temperatures_w1 array.

# shape
temp_w1.shape

(7,)

In [7]:
# --- Inspection and Properties ---

# 1. Shape of the array
print(f"\n1. Shape of the array: {temperatures_w1.shape}")

1. Shape of the array: (7,)

In [8]:
# 2. Data type of the array
print(f"2. Data type (dtype): {temperatures_w1.dtype}")

2. Data type (dtype): float64

In [9]:
# 3. Number of elements in the array
print(f"3. Number of elements (size): {temperatures_w1.size}")

3. Number of elements (size): 7

In [11]:
# Complete Inspection Summary ---
print("\n--- Complete Inspection Summary ---")
print(f"Array = {temperatures_w1}")
print(f"Shape = {temperatures_w1.shape} -> Means 1D array with 7 elements")
print(f"dtype = {temperatures_w1.dtype} -> Means float values")
print(f"size = {temperatures_w1.size} -> Total 7 temperatures")
print(f"ndim = {temperatures_w1.ndim} -> 1-Dimensional array")

--- Complete Inspection Summary ---
Array = [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Shape = (7,) -> Means 1D array with 7 elements
dtype = float64 -> Means float values
size = 7 -> Total 7 temperatures
ndim = 1 -> 1-Dimensional array

In [12]:
import numpy as np

# Given array - Week 1 temperatures in Celsius
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Original Array (Celsius):")
print(temperatures_w1)

# --- 1. Convert Celsius to Fahrenheit ---
# Formula: Fahrenheit = (Celsius * 9/5) + 32
# NumPy does this for the whole array at once (Vectorization)

temperatures_f = (temperatures_w1 * 9/5) + 32

print("\nConverted Array (Fahrenheit):")
print(temperatures_f)
print(f"Formatted: {np.round(temperatures_f, 2)}")

Original Array (Celsius):
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Converted Array (Fahrenheit):
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Formatted: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [13]:
# --- 2. Find Maximum, Minimum, and Mean (Original)---

max_temp = np.max(temperatures_w1)
min_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)

print("\n--- Week 1 Temperature Analysis ---")
print(f"Maximum Temperature: {max_temp} °C")
print(f"Minimum Temperature: {min_temp} °C")
print(f"Mean (Average) Temperature: {mean_temp:.2f} °C")

--- Week 1 Temperature Analysis ---
Maximum Temperature: 26.1 °C
Minimum Temperature: 20.8 °C
Mean (Average) Temperature: 23.54 °C

In [18]:
# --- 2. Find Maximum, Minimum, and Mean (Converted Array (Fahrenheit))---
print("\n--- In Fahrenheit ---")
print(f"Maximum Temperature: {np.max(temperatures_f):.2f} °F")
print(f"Minimum Temperature: {np.min(temperatures_f):.2f} °F")
print(f"Mean Temperature: {np.mean(temperatures_f):.2f} °F")

--- In Fahrenheit ---
Maximum Temperature: 78.98 °F
Minimum Temperature: 69.44 °F
Mean Temperature: 74.38 °F

In [21]:
import numpy as np

# Given array - Week 1
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

# Index mapping for clarity:
# Day: Mon Tue Wed Thu Fri Sat Sun
# Index: 0 1 2 3 4 5 6
# Value: 22.5 25.3 20.8 23.4 26.1 24.8 21.9

print(f"Full Week: {temperatures_w1}")

# --- 1. Extract temperatures for the first three days of the week ---
# Days: Monday, Tuesday, Wednesday -> Index 0, 1, 2
# Slicing: [0:3] means start at 0, go up to (but not including) 3

first_three_days = temperatures_w1[0:3]
# Alternative short form: temperatures_w1[:3]

print("\n1. First three days (Mon-Wed):")
print(first_three_days)

Full Week: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

1. First three days (Mon-Wed):
[22.5 25.3 20.8]

In [22]:
# --- 2. Extract temperatures for the weekend (last two days) ---
# Days: Saturday, Sunday -> Index 5, 6
# Slicing: [5:7] or [-2:] (last 2 elements)

weekend_temps = temperatures_w1[5:7]
# Best way: temperatures_w1[-2:]

weekend_temps_short = temperatures_w1[-2:]

print("\n2. Weekend (Sat-Sun) - Last two days:")
print(weekend_temps)
print(f"Using negative index [-2:]: {weekend_temps_short}")

2. Weekend (Sat-Sun) - Last two days:
[24.8 21.9]
Using negative index [-2:]: [24.8 21.9]

In [23]:
# --- 3. Extract temperatures for the middle three days ---
# Days: Wednesday, Thursday, Friday -> Index 2, 3, 4
# Slicing: [2:5]

middle_three_days = temperatures_w1[2:5]

print("\n3. Middle three days (Wed-Thu-Fri):")
print(middle_three_days)

3. Middle three days (Wed-Thu-Fri):
[20.8 23.4 26.1]

In [24]:
# Converted Array (Fahrenheit):
temp_fa=(temp_w1 * 9/5)+32

print('Temperature in Fahrenheit :', temp_fa)

Temperature in Fahrenheit : [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [25]:
# Converted Array (Fahrenheit):
# First three days (index 0,1,2)
# Weekend (last two days → index 5,6)
# Middle three days (index 2,3,4)
print('Slicing and Indexing(Temperatures)')
print('\nTemp for the first three days   :', temp_fa[0:3])
print('Temp for the last two days      :', temp_fa[-2:])
print('Temp for the middle three days  :', temp_fa[2:5])

Slicing and Indexing(Temperatures)

Temp for the first three days   : [72.5  77.54 69.44]
Temp for the last two days      : [76.64 71.42]
Temp for the middle three days  : [69.44 74.12 78.98]

In [26]:
import numpy as np

# Given data
week1 = [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
week2 = [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]

# --- 1. Create a 2D NumPy array named temperatures ---
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], # Row 1 - Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] # Row 2 - Week 2
])

print("2D Array - temperatures:")
print(temperatures)

2D Array - temperatures:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [28]:
# --- PART 1: Inspect shape, data type, total elements ---

print("\n--- 1. Inspection ---")
print(f"Shape: {temperatures.shape} -> Means {temperatures.shape[0]} weeks, {temperatures.shape[1]} days per week")
print(f"Data Type (dtype): {temperatures.dtype}")
print(f"Total number of elements (size): {temperatures.size}")
print(f"Dimensions (ndim): {temperatures.ndim}")
print(f"Number of rows: {temperatures.shape[0]}")
print(f"Number of columns: {temperatures.shape[1]}")

--- 1. Inspection ---
Shape: (2, 7) -> Means 2 weeks, 7 days per week
Data Type (dtype): float64
Total number of elements (size): 14
Dimensions (ndim): 2
Number of rows: 2
Number of columns: 7

In [29]:
# --- PART 2: Slice the 2D Array ---

print("\n--- 2. Slicing ---")

# Extract temperatures for each week
week1_temps = temperatures[0, :] # Row 0, all columns
week2_temps = temperatures[1, :] # Row 1, all columns

print(f"\nWeek 1 Temperatures (Row 0): {week1_temps}")
print(f"Week 2 Temperatures (Row 1): {week2_temps}")

# Extract weekends (last two days) for both weeks
# All rows, columns 5 and 6 (Saturday & Sunday)
# Syntax: array[rows, columns] -> [:, 5:7]

weekend_both_weeks = temperatures[:, 5:7]

print(f"\nWeekends (Last 2 days) for Both Weeks:")
print(weekend_both_weeks)
# Output:
# [[24.8 21.9] <- Week 1 weekend
# [22.8 20.1]] <- Week 2 weekend

# Extract weekend for each week separately
week1_weekend = temperatures[0, 5:7]
week2_weekend = temperatures[1, 5:7]

print(f"\nWeek 1 Weekend only: {week1_weekend}")
print(f"Week 2 Weekend only: {week2_weekend}")

--- 2. Slicing ---

Week 1 Temperatures (Row 0): [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 Temperatures (Row 1): [19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekends (Last 2 days) for Both Weeks:
[[24.8 21.9]
 [22.8 20.1]]

Week 1 Weekend only: [24.8 21.9]
Week 2 Weekend only: [22.8 20.1]

**Pandas Series**

In [31]:
import pandas as pd

# --- 1. Creating Pandas Series with Custom Indices ---

marks_data = [95, 92, 89, 85, 80]
custom_index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']

marks = pd.Series(data=marks_data, index=custom_index)

print("Pandas Series - marks:")
print(marks)

Pandas Series - marks:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [38]:
import pandas as pd

# Create Series
marks = pd.Series([95, 92, 89, 85, 80],
                  index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

print("Original Series:")
print(marks)

Original Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [51]:
import pandas as pd

# Create Series
marks = pd.Series([95, 92, 89, 85, 80],
                  index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

print("Original Series:")
print(marks)

# --- 1. Use integer index position to access mark of 1st rank student ---
# 1st rank is at position 0 (or index label 'Rank1')
first_rank_mark_pos = marks.iloc[0] # FIXED: was marks[0]
print("\n1. Mark of 1st rank student (integer position):")
print(f"marks[0] = {first_rank_mark_pos}")

# --- 2. Use loc accessor to retrieve marks of top 3 ranks by index labels ---
# loc uses LABELS -> 'Rank1' to 'Rank3'
top_3_ranks = marks.loc['Rank1':'Rank3']
# Alternative: marks.loc[['Rank1', 'Rank2', 'Rank3']]

print("\n2. Top 3 ranks using.loc (by labels):")
print(top_3_ranks)

# --- 3. Use iloc accessor to retrieve mark of 3rd-ranked student ---
# iloc uses POSITION -> 3rd rank is at position 2
third_rank_mark = marks.iloc[2]

print("\n3. Mark of 3rd-ranked student using.iloc[2]:")
print(third_rank_mark)

# --- 4. Boolean mask to filter marks > 90 ---
# Create a boolean mask
mask = marks[marks > 90]
print("\n4. Boolean Mask (marks > 90):")
print(mask)

filtered_marks = marks[marks > 90]

print("\nFiltered Ranks where marks > 90:")
print(filtered_marks)

Original Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

1. Mark of 1st rank student (integer position):
marks[0] = 95

2. Top 3 ranks using.loc (by labels):
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3. Mark of 3rd-ranked student using.iloc[2]:
89

4. Boolean Mask (marks > 90):
Rank1    95
Rank2    92
dtype: int64

Filtered Ranks where marks > 90:
Rank1    95
Rank2    92
dtype: int64

In [50]:
import pandas as pd

# Create Series
marks = pd.Series([95, 92, 89, 85, 80],
                  index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

print("Original Series:")
print(marks)

# --- 1. FIXED: Use iloc for integer position ---
first_rank_mark_pos = marks.iloc[0] # FIXED: was marks[0]

print("\n1. Mark of 1st rank student (integer position):")
print(f"marks.iloc[0] = {first_rank_mark_pos}")

# --- 2. Use loc for labels ---
top_3_ranks = marks.loc['Rank1':'Rank3']
print("\n2. Top 3 ranks using.loc:")
print(top_3_ranks)

# --- 3. Use iloc for position ---
third_rank_mark = marks.iloc[2]
print("\n3. Mark of 3rd-ranked student using.iloc[2]:")
print(third_rank_mark)

# --- 4. Boolean mask ---
filtered_marks = marks[marks > 90]
print("\n4. Filtered Ranks where marks > 90:")
print(filtered_marks)

Original Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

1. Mark of 1st rank student (integer position):
marks.iloc[0] = 95

2. Top 3 ranks using.loc:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3. Mark of 3rd-ranked student using.iloc[2]:
89

4. Filtered Ranks where marks > 90:
Rank1    95
Rank2    92
dtype: int64

In [52]:
import pandas as pd

# Initial Series
marks = pd.Series([95, 92, 89, 85, 80],
                  index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

print("Original Series:")
print(marks)

# --- 1. Modify the mark of 1st rank student to 100 ---
marks.loc['Rank1'] = 100
# or marks['Rank1'] = 100

print("\n1. After modifying Rank1 to 100:")
print(marks)

Original Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

1. After modifying Rank1 to 100:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [53]:
# --- 2. Remove the entry corresponding to last rank ---
marks = marks.drop('Rank5')
# To remove by position: marks = marks.drop(marks.index[-1])

print("\n2. After removing last rank (Rank5):")
print(marks)

2. After removing last rank (Rank5):
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [55]:
# --- 3. Compute CGPA by dividing each mark by 10 ---
cgpa = marks / 10
# or cgpa = marks.div(10)

print('Marks:\n'+str(marks))
print()

print("\n3. CGPA (marks / 10):")
print(cgpa)

Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


3. CGPA (marks / 10):
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

***Pandas DataFrame***

**# 1. Creating Pandas DataFrame:**

In [60]:
import pandas as pd

# --- Creating Pandas DataFrame named transactions ---

data={
    "TransactionID" : [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory": ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    "Region"         : ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South','North'],
    "Amount"        :[ 200, 150, 300, 450, 200, 250, 300, 180, 350, 400]

}
df_data=pd.DataFrame(data)
df_data

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [62]:
data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions = pd.DataFrame(data)

df_data=pd.DataFrame(data)
df_data

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [65]:
# ● Display the transactions DataFrame and its basic information, including head, tail,
# shape, column names, and data types.
df_data.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [66]:
#tail()
df_data.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [67]:
#shape
df_data.shape

(10, 4)

In [70]:
#column name
df_data.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [71]:
#data type
df_data.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [72]:
## ● Display only the 'ProductCategory' and 'Amount' columns.
df_data[['ProductCategory','Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [73]:
## ● Display only the 'ProductCategory' and 'Amount' columns.
df_data[['ProductCategory','Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [74]:
# ● Retrieve the last 3 columns of the DataFrame using iloc or loc.
# Last 3 columns
df_data.iloc[:, -3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [75]:
# ● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
filter_df= df_data[(df_data['Region'] == 'North') & (df_data['Amount'] > 200)]
print(filter_df)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [76]:
# ● Find the value counts for the 'ProductCategory' column.
df_data['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [77]:
# ● Find the unique values in the 'Region' column.
df_data['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [78]:
# ● Group by 'Region' and find the mean amount for each region.
mean_amount = df_data.groupby('Region')['Amount'].mean()
print(mean_amount)

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [79]:
# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
import pandas as pd

# 1. Modify 'Amount' for TransactionID 102 to 165
df_data.loc[df_data['TransactionID'] == 102, 'Amount'] = 165


print(df_data)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [80]:
# 2. Add a new column 'Discount' (10% of Amount)
df_data['Discount'] = df_data['Amount'] * 0.10
print(df_data)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [81]:
# 3. Remove the row with TransactionID 109
df_data = df_data[df_data['TransactionID'] != 109]
print(df_data)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [82]:
# 4. Delete the 'Discount' column
df_data = df_data.drop(columns=['Discount'])
print(df_data)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

**Thank You**